
/**
 * Generated by https://github.com/dsheiko/puppetry
 * on Sun Nov 20 2022 21:39:20 GMT+0900 (日本標準時)
 * Suite: Sandbox GA
 */

var nVer = process.version.match( /^v(\d+)/ );
if ( !nVer || nVer[ 1 ] < 9 ) {
  console.error( "WARNING: You have an outdated Node.js version " + process.version
    + ". You need at least v.9.x to run this test suite." );
}


const {
        bs, util, fetch, localStorage
      } = require( "../lib/bootstrap" )( "Sandbox--GA" ),
      puppeteerOptions = require( "../puppeteer.config.json" ),
      devices = require( "puppeteer" ).devices,
      fs = require( "fs" ),
      path = require( "path" ),
      os = require( "os" );




jest.setTimeout( 50000 );

let consoleLog = [], // assetConsoleMessage
    dialogLog = []; // assertDialog;

bs.TARGETS = {};

// Environment variables
let ENV = {
  "SANDBOX_BASEURL": "https://puppetry.app/demo/"
};

bs.TARGETS[ "FIRSTNAME_INPUT" ] = async () => await bs.query( "#fname", true, "FIRSTNAME_INPUT" );
bs.TARGETS[ "LASTNAME_INPUT" ] = async () => await bs.query( "#lname", true, "LASTNAME_INPUT" );
bs.TARGETS[ "MESSAGE_INPUT" ] = async () => await bs.query( "#comment", true, "MESSAGE_INPUT" );
bs.TARGETS[ "CONSENT_CHECKBOX" ] = async () => await bs.query( "#consent", true, "CONSENT_CHECKBOX" );
bs.TARGETS[ "OPTION_RADIO_1" ] = async () => await bs.query( "#option1", true, "OPTION_RADIO_1" );
bs.TARGETS[ "ATTACHMENT_FILE" ] = async () => await bs.query( "#attachment", true, "ATTACHMENT_FILE" );
bs.TARGETS[ "FORM" ] = async () => await bs.query( "#form", true, "FORM" );
bs.TARGETS[ "SUBMIT_BTN" ] = async () => await bs.query( "#submit", true, "SUBMIT_BTN" );
bs.TARGETS[ "ADD_TO_CART_BTN" ] = async () => await bs.query( "#addtocartwhite", true, "ADD_TO_CART_BTN" );
bs.TARGETS[ "CHECKOUT_BTN" ] = async () => await bs.query( "#checkoutbtn", true, "CHECKOUT_BTN" );
bs.TARGETS[ "PROCEED_BTN" ] = async () => await bs.query( "#proceedbtn", true, "PROCEED_BTN" );
bs.TARGETS[ "PURCHASE_BTN" ] = async () => await bs.query( "#purchasebtn", true, "PURCHASE_BTN" );
bs.TARGETS[ "PAYMENT_METHOD_SELECT" ] = async () => await bs.query( "#paymentmethod", true, "PAYMENT_METHOD_SELECT" );

describe( "Sandbox GA", () => {
  beforeAll(async () => {
    await bs.setup( puppeteerOptions, {"allure":false,"requireInterceptTraffic":true});
    await util.once(async () => {
      bs.browser && console.log( "BROWSER: ", await bs.browser.version() );
      await util.savePuppetterInfo( bs );
    });

    bs.page.on( "console", ( message ) => consoleLog.push( message ) );
    bs.page.on( "dialog", ( dialog ) => dialogLog.push( dialog ) );

    
    bs.performance.watchTraffic();

    
  });

  afterAll(async () => {

    await bs.teardown();
  });


  describe( "Performance Budget", () => {

    test( "Main page {dduk2fx8bwf}", async () => {
      let result, assert, searchStr, localEnv;

      // Defining browser viewport
      await bs.page.setViewport({
        width: 1920,
        height: 1080,
        deviceScaleFactor: 1,
        isMobile: false,
        hasTouch: false,
        isLandscape: false
      });
  

      // Navigating to {{ SANDBOX_BASEURL }}
      bs.performance.reset();
      await bs.page.goto( `${ ENV[ "SANDBOX_BASEURL" ] }`, {"timeout":30000,"waitUntil":"load"} );
    
      
      // Asserting that total weight of assets satisfies the given budget
      util.saveResourceReport( "dduk2fxb5yw", bs.performance.resources )
      
      result = bs.performance.resources;       
      expect( result ).toMatchAssetWeight( "script", 200000, "page.assertPerformanceAssetWeight" );       
      expect( result ).toMatchAssetWeight( "stylesheet", 50000, "page.assertPerformanceAssetWeight" );       
      expect( result ).toMatchAssetWeight( "image", 1500000, "page.assertPerformanceAssetWeight" ); 
      
      // Asserting that total number of assets satisfies the given budget
      result = bs.performance.resources;       
      expect( result ).toMatchAssetCount( "script", 6, "page.assertPerformanceAssetCount" );       
      expect( result ).toMatchAssetCount( "stylesheet", 10, "page.assertPerformanceAssetCount" );       
      expect( result ).toMatchAssetCount( "image", 100, "page.assertPerformanceAssetCount" ); 
      
      // Asserting timing
      
      result = JSON.parse( await bs.page.evaluate( () => JSON.stringify( window.performance.timing ) ) );       
      expect( result ).toMatchTiming( "loading", 4000, "page.assertPerformanceTiming" );       
      expect( result ).toMatchTiming( "network", 1250, "page.assertPerformanceTiming" );       
      expect( result ).toMatchTiming( "processing", 3500, "page.assertPerformanceTiming" ); 
    });

  });


});
